# Pandas III

### Index alignment in Series

In [8]:
import numpy as np
import pandas as pd

In [2]:
area = pd.Series({'Alaska':1723337, 'Texas':695662,
                'California': 423967}, name ='area')
population = pd.Series({'California':38332521, 'Texas': 26448193,
                      'New York': 19651127}, name='population')

In [3]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [4]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])

In [5]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [6]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in Series

In [11]:
A = pd.DataFrame(np.random.randint(0,20,(2,2)),
                 columns=list('AB'))
A
                    

A   B
0  17  10
1  13   3

In [12]:
B = pd.DataFrame(np.random.randint(0,10,(3,3)),
                 columns=list('BAC'))
B

B  A  C
0  7  3  1
1  8  7  2
2  0  1  7

In [13]:
A+B

A     B   C
0  20.0  17.0 NaN
1  20.0  11.0 NaN
2   NaN   NaN NaN

In [14]:
# Fill NaN by mean
fill = A.stack().mean()
A.add(B, fill_value=fill)

A      B      C
0  20.00  17.00  11.75
1  20.00  11.00  12.75
2  11.75  10.75  17.75

In [16]:
A = np.random.randint(10, size=(3,4))
A

array([[3, 2, 1, 5],
       [9, 3, 3, 0],
       [9, 6, 5, 8]])

In [17]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 6,  1,  2, -5],
       [ 6,  4,  4,  3]])

In [19]:
# In pandas, the convention similarly operates row-wise by default:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  6  1  2 -5
2  6  4  4  3

In [20]:
# instead like to operate column-wise.
df.subtract(df['R'], axis=0)

Q  R  S  T
0  1  0 -1  3
1  6  0  0 -3
2  3  0 -1  2

# Missing Data in Pandas : None VS Nan ?

## None

In [21]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [22]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

## NaN

In [24]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [25]:
vals2

array([ 1., nan,  3.,  4.])

In [27]:
vals2.sum()

nan

In [28]:
vals2.min()

nan

In [29]:
vals2.max()

nan

In [30]:
np.nansum(vals2)

8.0

In [31]:
np.nanmin(vals2)

1.0

In [32]:
np.nanmax(vals2)

4.0

In [33]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [34]:
x =pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [35]:
x[0]=None
x

0    NaN
1    1.0
dtype: float64

## Operating on Null Values

### Detecting null values

In [36]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [37]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [38]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [39]:
data = pd.Series([1, np.nan, 'hello', None])

In [40]:
data.dropna()

0        1
2    hello
dtype: object

In [43]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, np.nan],
                  [np.nan, 4, 6]])
df

0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  NaN
2  NaN  4.0  6.0

In [42]:
df.dropna()

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [44]:
df.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2]

## Filling Null Values

In [47]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [46]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [48]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [49]:
# Back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

## Hierarchical Indexing : Multiply Indexed Seiries

In [124]:
index = [('California',2000),('California',2010),
        ('New York',2000), ('New York', 2010),
        ('Texas',2000), ('Texas',2010)]
populations =[33871648, 37253956,
             18976457, 19378102,
             20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [127]:
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [125]:
pop[('California',2010):('Texas',2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [78]:
print(pop[1])
print(pop[3])
print(pop[5])

37253956
19378102
25145561


## Pandas MultiIndex

In [126]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [128]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [129]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [122]:
index = [('California',2000),('California',2010),
        ('New York',2000), ('New York', 2010),
        ('Texas',2000), ('Texas',2010)]
populations =[33871648, 37253956,
             18976457, 19378102,
             20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [130]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [132]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [133]:
pop_df = pd.DataFrame({'total':pop,
                      'under18':[9267089, 9284094,
                                4687374, 4318033,
                                5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [135]:
f_u18 = pop_df['under18']/pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

## Methods of MultiIndex Creation

In [137]:
df = pd.DataFrame(np.random.rand(4, 2),
                 index = [['a','a','b','b'],[1,2,1,2]],
                 columns=['data1','data2'])
df

data1     data2
a 1  0.156897  0.904277
  2  0.338555  0.093182
b 1  0.133534  0.971095
  2  0.739303  0.109666

In [138]:
data= {('California',2000):33871648, 
      ('California',2010):37253956,
      ('New York',2000):18976457, 
      ('New York', 2010):19378102,
      ('Texas',2000):20851820, 
      ('Texas',2010):25145561}
pd.Series(data)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
# Continue Combining Datasets